version: '3.7'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'UTC'
      MYSQL_DATABASE: eduqat


