service: serverless-http-api-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getById:
    handler: handler.getById
    events:
      - httpApi:
          path: /v1/courses/{id}
          method: get
  getAll:
    handler: handler.getAll
    events:
      - httpApi:
          path: /v1/courses
          method: get
  addNew:
    handler: handler.addNew
    events:
      - httpApi:
          path: /v1/courses
          method: post
  edit:
    handler: handler.edit
    events:
      - httpApi:
          path: /v1/courses/{id}
          method: put
  deleteById:
    handler: handler.deleteById
    events:
      - httpApi:
          path: /v1/courses/{id}
          method: delete

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline
